(() => {
  const STORE='contrack_hangingsense_v4_4';
  const LEGACY_KEYS=['contrack_hangingsense_v4_3','contrack_hangingsense_v4_2','contrack_v3_1_state'];
  const DB='contrack_media_v1', PHOTO_STORE='photos';
  const THEMES=[
    {id:'hanging',name:'Copper Glow',colors:['#fff6ea','#7b2f0e','#f39a32']},
    {id:'terracotta',name:'Terracotta Bloom',colors:['#fff1e9','#983f28','#ed8c65']},
    {id:'sage',name:'Sage & Copper',colors:['#f3f6ed','#365944','#c37432']},
    {id:'plum',name:'Plum Ember',colors:['#f8f0f6','#60304e','#d47a42']},
    {id:'night',name:'Midnight Copper',colors:['#101217','#f0a45d','#ffb259']},
    {id:'ivory',name:'Ivory Minimal',colors:['#fbf8f0','#2f2923','#b97834']}
  ];
  const LANGS=[['en','🇬🇧 English'],['de','🇩🇪 Deutsch'],['fr','🇫🇷 Français'],['es','🇪🇸 Español'],['fa','🇮🇷 فارسی'],['zh','🇨🇳 中文'],['hi','🇮🇳 हिन्दी'],['ar','🇸🇦 العربية'],['ru','🇷🇺 Русский'],['ko','🇰🇷 한국어'],['ja','🇯🇵 日本語']];
  const EN={
    companion:'your labour companion',trackKicker:'Contraction timer',ready:'Ready',tapWhenBegins:'Tap when a contraction begins',start:'Start',stop:'Stop',recording:'Recording',inProgress:'Contraction in progress',
    lastContraction:'Last contraction',noneYet:'None recorded yet',recentRhythm:'Recent rhythm',lastFive:'Last 5 contractions',track:'Track',history:'History',summary:'Summary',more:'More',
    historySubtitle:'Contractions and events in one timeline',today:'Today',all:'All',day:'Day',time:'Time',event:'Event',details:'Details',duration:'Duration',interval:'Interval',intensity:'Pain intensity',
    summarySubtitle:'A factual report of recorded timing, intensity and events',contractionPattern:'Contraction pattern',startToStart:'start-to-start',events:'Events',timelineReport:'Timeline report',timelineReportHint:'Includes cumulative averages to show the recorded trend.',
    shareReport:'Share full report',downloadReport:'Download / save report',appearance:'Appearance',appearanceHint:'Six distinct palettes remain harmonious with the copper Hanging Sense identity.',language:'Language',sessions:'Sessions',
    newSession:'Start new session',backupSession:'Backup current session + photos',restoreBackup:'Restore backup',exportCsv:'Export CSV',brandStatement:'A calm, local-first labour companion with a human identity.',
    addEvent:'Add event',addEventHint:'Pee, pain, waters, bleeding or other',saved:'Contraction saved',howIntense:'How intense was it?',low:'Low',moderate:'Moderate',strong:'Strong',intense:'Intense',save:'Save',later:'Later',
    pee:'Pee',painEvent:'Pain / discomfort',waters:'Waters / fluid',bleeding:'Bleeding',other:'Other',notes:'Note (optional)',addPhoto:'Add photo',photoLocal:'Stored only on this device',saveEvent:'Save event',cancel:'Cancel',
    protectHistory:'Protect your history first',protectHistoryText:'This session contains recorded data. Back it up with photos or archive it in the app before starting again.',backupAndNew:'Download backup & start new',archiveAndNew:'Archive in app & start new',
    contractions:'Contractions',avgDuration:'Avg duration',avgInterval:'Avg interval',latestPain:'Latest pain',noData:'No data in this range.',eventSaved:'Event saved.',photoReady:'Photo ready · stored locally',reportReady:'Report prepared.',restored:'Backup restored.',
    exportReport:'Export report',exportReportHint:'Choose a format for the currently selected Summary range.',picturePng:'Picture / PNG',picturePngHint:'Easy to save, send or print',htmlReport:'HTML report',htmlReportHint:'Full chart, timeline, notes and photos'
  };
  const DE={trackKicker:'Wehentimer',ready:'Bereit',tapWhenBegins:'Tippen, wenn eine Wehe beginnt',start:'Start',stop:'Stopp',recording:'Aufzeichnung',inProgress:'Wehe läuft',lastContraction:'Letzte Wehe',noneYet:'Noch keine Wehe erfasst',recentRhythm:'Letzter Rhythmus',lastFive:'Letzte 5 Wehen',track:'Track',history:'Verlauf',summary:'Übersicht',more:'Mehr',historySubtitle:'Wehen und Ereignisse in einer gemeinsamen Zeitleiste',today:'Heute',all:'Alle',day:'Tag',time:'Zeit',event:'Ereignis',details:'Details',duration:'Dauer',interval:'Intervall',intensity:'Schmerzintensität',summarySubtitle:'Sachlicher Bericht zu Zeiten, Intensität und Ereignissen',contractionPattern:'Wehenmuster',startToStart:'Start-zu-Start',events:'Ereignisse',timelineReport:'Zeitleistenbericht',timelineReportHint:'Mit kumulativen Mittelwerten, um den erfassten Trend sichtbar zu machen.',shareReport:'Vollständigen Bericht teilen',downloadReport:'Bericht speichern',appearance:'Design',appearanceHint:'Sechs deutlich unterschiedliche Farbwelten mit Bezug zur kupferfarbenen Hanging-Sense-Identität.',language:'Sprache',sessions:'Sitzungen',newSession:'Neue Sitzung starten',backupSession:'Aktuelle Sitzung + Fotos sichern',restoreBackup:'Sicherung wiederherstellen',exportCsv:'CSV exportieren',brandStatement:'Ein ruhiger, lokaler Geburtsbegleiter mit menschlicher Identität.',addEvent:'Ereignis hinzufügen',addEventHint:'Toilette, Schmerz, Fruchtwasser, Blutung oder anderes',saved:'Wehe gespeichert',howIntense:'Wie intensiv war die Wehe?',low:'Leicht',moderate:'Mittel',strong:'Stark',intense:'Sehr stark',save:'Speichern',later:'Später',pee:'Toilette',painEvent:'Schmerz / Unwohlsein',waters:'Fruchtwasser / Flüssigkeit',bleeding:'Blutung',other:'Anderes',notes:'Notiz (optional)',addPhoto:'Foto hinzufügen',photoLocal:'Wird nur auf diesem Gerät gespeichert',saveEvent:'Ereignis speichern',cancel:'Abbrechen',protectHistory:'Verlauf zuerst sichern',protectHistoryText:'Diese Sitzung enthält Daten. Sichere sie inklusive Fotos oder archiviere sie in der App, bevor du neu startest.',backupAndNew:'Sicherung laden & neu starten',archiveAndNew:'In App archivieren & neu starten',contractions:'Wehen',avgDuration:'Ø Dauer',avgInterval:'Ø Intervall',latestPain:'Letzter Schmerz',noData:'Keine Daten in diesem Zeitraum.',eventSaved:'Ereignis gespeichert.',photoReady:'Foto bereit · lokal gespeichert',reportReady:'Bericht erstellt.',restored:'Sicherung wiederhergestellt.',exportReport:'Bericht exportieren',exportReportHint:'Wähle ein Format für den aktuell ausgewählten Zeitraum.',picturePng:'Bild / PNG',picturePngHint:'Einfach speichern, senden oder drucken',htmlReport:'HTML-Bericht',htmlReportHint:'Vollständiges Diagramm, Verlauf, Notizen und Fotos'};
  const I18N={
    en:EN,de:{...EN,...DE},
    fr:{...EN,trackKicker:'Minuteur de contractions',ready:'Prête',tapWhenBegins:'Touchez quand une contraction commence',start:'Démarrer',stop:'Arrêter',history:'Historique',summary:'Résumé',more:'Plus',today:'Aujourd’hui',all:'Tout',day:'Jour',language:'Langue',appearance:'Apparence',save:'Enregistrer',later:'Plus tard',addEvent:'Ajouter un événement',contractions:'Contractions',duration:'Durée',interval:'Intervalle',intensity:'Douleur',events:'Événements'},
    es:{...EN,trackKicker:'Temporizador de contracciones',ready:'Lista',tapWhenBegins:'Toca cuando comience una contracción',start:'Iniciar',stop:'Detener',history:'Historial',summary:'Resumen',more:'Más',today:'Hoy',all:'Todo',day:'Día',language:'Idioma',appearance:'Apariencia',save:'Guardar',later:'Más tarde',addEvent:'Añadir evento',contractions:'Contracciones',duration:'Duración',interval:'Intervalo',intensity:'Dolor',events:'Eventos'},
    fa:{...EN,trackKicker:'زمان‌سنج انقباض',ready:'آماده',tapWhenBegins:'با شروع انقباض لمس کنید',start:'شروع',stop:'توقف',history:'تاریخچه',summary:'خلاصه',more:'بیشتر',today:'امروز',all:'همه',day:'روز',language:'زبان',appearance:'ظاهر',save:'ذخیره',later:'بعداً',addEvent:'افزودن رویداد',contractions:'انقباض‌ها',duration:'مدت',interval:'فاصله',intensity:'شدت درد',events:'رویدادها'},
    zh:{...EN,trackKicker:'宫缩计时器',ready:'准备好',tapWhenBegins:'宫缩开始时点击',start:'开始',stop:'停止',history:'记录',summary:'总结',more:'更多',today:'今天',all:'全部',day:'当天',language:'语言',appearance:'外观',save:'保存',later:'稍后',addEvent:'添加事件',contractions:'宫缩',duration:'持续时间',interval:'间隔',intensity:'疼痛强度',events:'事件'},
    hi:{...EN,trackKicker:'कॉन्ट्रैक्शन टाइमर',ready:'तैयार',tapWhenBegins:'कॉन्ट्रैक्शन शुरू होने पर टैप करें',start:'शुरू',stop:'रोकें',history:'इतिहास',summary:'सारांश',more:'अधिक',today:'आज',all:'सभी',day:'दिन',language:'भाषा',appearance:'डिज़ाइन',save:'सहेजें',later:'बाद में',addEvent:'इवेंट जोड़ें',contractions:'कॉन्ट्रैक्शन',duration:'अवधि',interval:'अंतराल',intensity:'दर्द तीव्रता',events:'इवेंट'},
    ar:{...EN,trackKicker:'مؤقت الانقباضات',ready:'جاهزة',tapWhenBegins:'اضغطي عند بدء الانقباض',start:'ابدئي',stop:'إيقاف',history:'السجل',summary:'الملخص',more:'المزيد',today:'اليوم',all:'الكل',day:'اليوم',language:'اللغة',appearance:'المظهر',save:'حفظ',later:'لاحقاً',addEvent:'إضافة حدث',contractions:'انقباضات',duration:'المدة',interval:'الفاصل',intensity:'شدة الألم',events:'أحداث'},
    ru:{...EN,trackKicker:'Таймер схваток',ready:'Готово',tapWhenBegins:'Нажмите при начале схватки',start:'Старт',stop:'Стоп',history:'История',summary:'Сводка',more:'Ещё',today:'Сегодня',all:'Все',day:'День',language:'Язык',appearance:'Оформление',save:'Сохранить',later:'Позже',addEvent:'Добавить событие',contractions:'Схватки',duration:'Длительность',interval:'Интервал',intensity:'Боль',events:'События'},
    ko:{...EN,trackKicker:'진통 타이머',ready:'준비',tapWhenBegins:'진통이 시작되면 탭하세요',start:'시작',stop:'종료',history:'기록',summary:'요약',more:'더보기',today:'오늘',all:'전체',day:'일',language:'언어',appearance:'디자인',save:'저장',later:'나중에',addEvent:'이벤트 추가',contractions:'진통',duration:'지속시간',interval:'간격',intensity:'통증 강도',events:'이벤트'},
    ja:{...EN,trackKicker:'陣痛タイマー',ready:'準備完了',tapWhenBegins:'陣痛が始まったらタップ',start:'開始',stop:'終了',history:'履歴',summary:'概要',more:'その他',today:'今日',all:'すべて',day:'日',language:'言語',appearance:'デザイン',save:'保存',later:'後で',addEvent:'イベント追加',contractions:'陣痛',duration:'持続時間',interval:'間隔',intensity:'痛み強度',events:'イベント'}
  };
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  let state=loadState(), tick=null, pendingEventType='pee', pendingPhotoBlob=null;
  function uid(p='x'){return `${p}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`}
  function freshState(){const sid=uid('s');return {version:'4.4',lang:'en',theme:'hanging',summaryRange:'60',historyFilter:'today',currentSessionId:sid,sessions:[{id:sid,createdAt:Date.now(),archived:false,contractions:[],events:[]}],activeStart:null,pendingIntensityId:null}}
  function normalizeState(s){s={...freshState(),...s};s.sessions=(s.sessions||[]).map(x=>({id:x.id||uid('s'),createdAt:x.createdAt||Date.now(),archived:!!x.archived,contractions:(x.contractions||[]).map(c=>({...c,start:+c.start,end:+c.end||(+c.start+(+c.durationSec||1)*1000),durationSec:+c.durationSec||Math.max(1,Math.round(((+c.end||+c.start+1000)-(+c.start))/1000)),intensity:Number.isFinite(+c.intensity)?+c.intensity:(Number.isFinite(+c.painIntensity)?+c.painIntensity:null),notes:c.notes||c.note||''})),events:x.events||[]}));if(!s.sessions.some(x=>x.id===s.currentSessionId))s.currentSessionId=s.sessions.at(-1)?.id||freshState().currentSessionId;s.version='4.4';return s}
  function loadState(){try{const v=JSON.parse(localStorage.getItem(STORE)||'null');if(v?.sessions)return normalizeState(v)}catch{}for(const key of LEGACY_KEYS){try{const x=JSON.parse(localStorage.getItem(key)||'null');if(x?.sessions){const v=normalizeState(x);localStorage.setItem(STORE,JSON.stringify(v));return v}if(x?.contractions){const v=freshState();v.sessions[0].contractions=(x.contractions||[]).map(c=>({id:c.id||uid('c'),start:+(c.start||Date.now()),end:+c.end||(+c.start+(+c.durationSec||1)*1000),durationSec:+c.durationSec||Math.max(1,Math.round(((+c.end||+c.start+1000)-(+c.start))/1000)),intensity:Number.isFinite(+c.intensity)?+c.intensity:null,notes:c.notes||''}));v.lang=x.lang||'en';v.theme=THEMES.some(t=>t.id===x.theme)?x.theme:'hanging';localStorage.setItem(STORE,JSON.stringify(v));return v}}catch{}}return freshState()}
  function persist(){localStorage.setItem(STORE,JSON.stringify(state))}
  function t(k){return I18N[state.lang]?.[k]||EN[k]||k}
  function cur(){return state.sessions.find(s=>s.id===state.currentSessionId)||state.sessions.at(-1)}
  function contractions(){return [...cur().contractions].sort((a,b)=>a.start-b.start)}
  function events(){return [...cur().events].sort((a,b)=>a.time-b.time)}
  function fmtClock(ts){return new Date(ts).toLocaleTimeString(state.lang,{hour:'2-digit',minute:'2-digit'})}
  function fmtDate(ts){return new Date(ts).toLocaleDateString(state.lang,{day:'numeric',month:'short'})}
  function fmtDur(sec){if(sec==null||!Number.isFinite(+sec))return '—';sec=Math.round(+sec);const m=Math.floor(sec/60),s=sec%60;return m?`${m}m ${String(s).padStart(2,'0')}s`:`${s}s`}
  function fmtAgo(ts){const s=Math.max(0,Math.floor((Date.now()-ts)/1000));if(s<60)return `${s}s ago`;const m=Math.floor(s/60);if(m<60)return `${m}m ago`;return `${Math.floor(m/60)}h ago`}
  function intervalFor(c,list=contractions()){const i=list.findIndex(x=>x.id===c.id);if(i<=0)return null;return Math.max(0,Math.round((c.start-list[i-1].start)/1000))}
  function rangeStart(){if(state.summaryRange==='all')return -Infinity;if(state.summaryRange==='day'){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()}return Date.now()-Number(state.summaryRange||60)*60000}
  function rangeData(){const since=rangeStart(),cs=contractions().filter(c=>c.start>=since),ev=events().filter(e=>e.time>=since);return {cs:cs.map((c,i)=>({...c,intervalSec:i>0?Math.max(0,Math.round((c.start-cs[i-1].start)/1000)):null})),ev}}
  function avg(nums){const a=nums.filter(Number.isFinite);return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
  function intensityLabel(v){v=+v;if(v<=2)return t('low');if(v<=5)return t('moderate');if(v<=7)return t('strong');return t('intense')}
  function eventMeta(type){return {pee:['🚻',t('pee')],pain:['⚡',t('painEvent')],waters:['💧',t('waters')],bleeding:['●',t('bleeding')],other:['＋',t('other')]}[type]||['＋',t('other')]}
  function applyTheme(){document.documentElement.dataset.theme=state.theme==='hanging'?'':state.theme;document.querySelector('meta[name="theme-color"]').content=getComputedStyle(document.documentElement).getPropertyValue('--bg').trim()||'#fff6ea'}
  function applyI18n(){document.documentElement.lang=state.lang;document.documentElement.dir=['ar','fa'].includes(state.lang)?'rtl':'ltr';$$('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));renderAll()}
  function toggleTimer(){if(!state.activeStart){state.activeStart=Date.now();persist();startTicker();renderTrackHero();navigator.vibrate?.(25);return}const end=Date.now(),c={id:uid('c'),start:state.activeStart,end,durationSec:Math.max(1,Math.round((end-state.activeStart)/1000)),intensity:null,notes:''};state.activeStart=null;state.pendingIntensityId=c.id;cur().contractions.push(c);persist();stopTicker();renderAll();openIntensity(c);navigator.vibrate?.([25,35,25])}
  function startTicker(){clearInterval(tick);tick=setInterval(renderTrackHero,500)}function stopTicker(){clearInterval(tick);tick=null}
  function renderTrackHero(){const active=!!state.activeStart;$('#timerButton').classList.toggle('active',active);if(active){const e=Math.floor((Date.now()-state.activeStart)/1000);$('#timerValue').textContent=`${String(Math.floor(e/60)).padStart(2,'0')}:${String(e%60).padStart(2,'0')}`;$('#timerCaption').textContent=t('stop');$('#heroState').textContent=t('recording');$('#heroSub').textContent=t('inProgress')}else{$('#timerValue').textContent=t('start').toUpperCase();$('#timerCaption').textContent=t('start');$('#heroState').textContent=t('ready');$('#heroSub').textContent=t('tapWhenBegins')}}
  function renderTrack(){renderTrackHero();const cs=contractions(),last=cs.at(-1);$('#lastValue').textContent=last?`${fmtDur(last.durationSec)} · ${fmtAgo(last.end)}`:t('noneYet');const r=$('#rhythm');r.innerHTML='';const bars=cs.slice(-5);if(!bars.length){r.innerHTML=`<div class="history-empty">${t('noData')}</div>`;return}const max=Math.max(30,...bars.map(x=>x.durationSec));bars.forEach(c=>{const item=document.createElement('div');item.className='rhythm-item';const h=30+(c.durationSec/max)*62;item.innerHTML=`<div class="rhythm-bar-wrap"><div class="pulse" style="height:${h}px" data-pain="${c.intensity==null?'':c.intensity}"></div></div><div class="rhythm-duration">${fmtDur(c.durationSec)}</div><div class="rhythm-pain">${c.intensity==null?t('intensity')+': —':t('intensity')+': '+c.intensity+'/10'}</div>`;r.appendChild(item)})}
  async function openDB(){return new Promise((res,rej)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(PHOTO_STORE))q.result.createObjectStore(PHOTO_STORE)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
  async function putPhoto(id,blob){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction(PHOTO_STORE,'readwrite');tx.objectStore(PHOTO_STORE).put(blob,id);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)})}
  async function getPhoto(id){if(!id)return null;const db=await openDB();return new Promise((res,rej)=>{const q=db.transaction(PHOTO_STORE).objectStore(PHOTO_STORE).get(id);q.onsuccess=()=>res(q.result||null);q.onerror=()=>rej(q.error)})}
  async function blobToDataURL(blob){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(fr.result);fr.onerror=rej;fr.readAsDataURL(blob)})}
  async function dataURLToBlob(url){const r=await fetch(url);return r.blob()}
  async function compressImage(file){const img=await createImageBitmap(file);const max=1280,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return new Promise(res=>c.toBlob(res,'image/jpeg',.76))}
  function openSheet(id){$('#sheetBackdrop').hidden=false;$(id).hidden=false}function closeSheets(){$('#sheetBackdrop').hidden=true;['#intensitySheet','#eventSheet','#sessionSheet','#exportSheet'].forEach(x=>$(x).hidden=true)}
  function openIntensity(c){$('#savedDuration').textContent=fmtDur(c.durationSec);$('#intensitySlider').value=c.intensity??5;syncIntensity();openSheet('#intensitySheet')}function syncIntensity(){const v=+$('#intensitySlider').value;$('#intensityNumber').textContent=v;$('#intensityLabel').textContent=intensityLabel(v)}function saveIntensity(){const c=cur().contractions.find(x=>x.id===state.pendingIntensityId);if(c)c.intensity=+$('#intensitySlider').value;state.pendingIntensityId=null;persist();closeSheets();renderAll()}function skipIntensity(){state.pendingIntensityId=null;persist();closeSheets()}
  function openEvent(){pendingEventType='pee';pendingPhotoBlob=null;$('#eventNote').value='';$('#eventPhoto').value='';$('#photoStatus').textContent=t('photoLocal');$$('#eventTypes button').forEach((b,i)=>b.classList.toggle('selected',i===0));openSheet('#eventSheet')}
  async function saveEvent(){let photoId=null;if(pendingPhotoBlob){photoId=uid('p');await putPhoto(photoId,pendingPhotoBlob)}cur().events.push({id:uid('e'),type:pendingEventType,time:Date.now(),note:$('#eventNote').value.trim(),photoId});persist();closeSheets();renderAll();toast(t('eventSaved'))}
  function combinedTimeline(){return [...contractions().map(c=>({kind:'contraction',time:c.start,...c})),...events().map(e=>({kind:'event',...e}))].sort((a,b)=>a.time-b.time)}
  function filterTimeline(items){if(state.historyFilter==='all')return items;const d=new Date(),start=new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime();return items.filter(x=>x.time>=start)}
  async function renderHistory(){$$('[data-history-filter]').forEach(b=>b.classList.toggle('active',b.dataset.historyFilter===state.historyFilter));const host=$('#historyList');host.innerHTML='';const items=filterTimeline(combinedTimeline());if(!items.length){host.innerHTML=`<div class="history-empty">${t('noData')}</div>`;return}const cs=contractions();let durSum=0,intSum=0,intN=0,conN=0;for(const it of items){const rec=document.createElement('article');rec.className='history-record'+(it.kind==='event'?' event-record':'');if(it.kind==='contraction'){conN++;durSum+=it.durationSec;const iv=intervalFor(it,cs);if(iv!=null){intSum+=iv;intN++}const pain=it.intensity==null?'—':`${it.intensity}/10`;rec.innerHTML=`<div class="history-record__top"><div class="history-record__time">${fmtClock(it.start)}<small>${fmtDate(it.start)}</small></div><div class="history-record__event">◉ ${t('contractions')}<small>${intensityLabel(it.intensity??0)}</small></div><div class="history-kpis"><span class="history-kpi"><small>${t('duration')}</small><b>${fmtDur(it.durationSec)}</b></span><span class="history-kpi"><small>${t('interval')}</small><b>${fmtDur(iv)}</b></span><span class="history-kpi"><small>${t('intensity')}</small><b>${pain}</b></span></div></div><div class="history-record__detail"><div class="history-record__detail-text"><strong>${t('avgDuration')}:</strong> ${fmtDur(durSum/conN)} · <strong>${t('avgInterval')}:</strong> ${fmtDur(intN?intSum/intN:null)}${it.notes?`<br>${escapeHtml(it.notes)}`:''}</div></div>`}else{const [ic,label]=eventMeta(it.type);rec.innerHTML=`<div class="history-record__top"><div class="history-record__time">${fmtClock(it.time)}<small>${fmtDate(it.time)}</small></div><div class="history-record__event">${ic} ${escapeHtml(label)}<small>${t('event')}</small></div><div class="history-kpis"><span class="history-kpi"><small>${t('details')}</small><b>${it.photoId?'📷':''}</b></span></div></div><div class="history-record__detail"><div class="history-record__detail-text">${it.note?escapeHtml(it.note):'—'}</div>${it.photoId?'<div class="photo-slot">…</div>':''}</div>`;if(it.photoId){getPhoto(it.photoId).then(blob=>{if(!blob)return;const img=document.createElement('img');img.className='history-photo';img.src=URL.createObjectURL(blob);rec.querySelector('.photo-slot')?.replaceWith(img)})}}host.appendChild(rec)}}
  function renderSummary(){$$('[data-range]').forEach(b=>b.classList.toggle('active',b.dataset.range===String(state.summaryRange)));const {cs,ev}=rangeData();$('#rangeDescription').textContent=state.summaryRange==='60'?'Last 1 hour':state.summaryRange==='180'?'Last 3 hours':state.summaryRange==='day'?'Today':'Entire session';drawChart(cs,ev);const ints=cs.map(x=>x.intervalSec).filter(Number.isFinite),pains=cs.map(x=>x.intensity).filter(Number.isFinite),cards=[[cs.length,t('contractions')],[fmtDur(avg(cs.map(x=>x.durationSec))),t('avgDuration')],[fmtDur(avg(ints)),t('avgInterval')],[pains.length?`${pains.at(-1)}/10`:'—',t('latestPain')],[ev.length,t('events')]];$('#metrics').innerHTML=cards.map(([v,l])=>`<div class="metric"><div class="value">${v}</div><div class="label">${l}</div></div>`).join('');renderReportTable(cs,ev)}
  function drawChart(cs,ev){const svg=$('#unifiedChart'),W=760,H=360,p={l:52,r:50,t:32,b:45};svg.innerHTML='';if(!cs.length&&!ev.length){svg.innerHTML=`<text x="380" y="180" text-anchor="middle" fill="var(--muted)">${t('noData')}</text>`;return}const ns='http://www.w3.org/2000/svg',mk=(tag,a={},txt='')=>{const e=document.createElementNS(ns,tag);Object.entries(a).forEach(([k,v])=>e.setAttribute(k,v));if(txt)e.textContent=txt;svg.appendChild(e);return e},times=[...cs.map(x=>x.start),...ev.map(x=>x.time)],min=Math.min(...times),max=Math.max(...times),span=Math.max(60000,max-min),x=ts=>p.l+(ts-min)/span*(W-p.l-p.r),maxDur=Math.max(60,...cs.map(c=>c.durationSec)),maxInt=Math.max(60,...cs.map(c=>c.intervalSec||0)),yDur=v=>H-p.b-(v/maxDur)*(H-p.t-p.b),yInt=v=>H-p.b-(v/maxInt)*(H-p.t-p.b),yPain=v=>H-p.b-(v/10)*(H-p.t-p.b);[0,.25,.5,.75,1].forEach(q=>{const y=p.t+(H-p.t-p.b)*q;mk('line',{x1:p.l,y1:y,x2:W-p.r,y2:y,stroke:'var(--line)','stroke-width':1})});cs.forEach(c=>{const bx=x(c.start)-9,by=yDur(c.durationSec);mk('rect',{x:bx,y:by,width:18,height:H-p.b-by,rx:7,fill:'var(--primary2)',opacity:.72});if(c.intensity!=null)mk('circle',{cx:x(c.start),cy:yPain(c.intensity),r:5.5,fill:'var(--rose)',stroke:'var(--surface)','stroke-width':2})});const pts=cs.filter(c=>c.intervalSec!=null).map(c=>`${x(c.start)},${yInt(c.intervalSec)}`);if(pts.length>1)mk('polyline',{points:pts.join(' '),fill:'none',stroke:'var(--teal)','stroke-width':3,'stroke-linejoin':'round','stroke-linecap':'round'});cs.forEach(c=>{if(c.intervalSec!=null)mk('circle',{cx:x(c.start),cy:yInt(c.intervalSec),r:4,fill:'var(--teal)'})});ev.forEach(e=>{const xx=x(e.time),yy=H-p.b-11;mk('rect',{x:xx-5,y:yy-5,width:10,height:10,transform:`rotate(45 ${xx} ${yy})`,fill:'var(--accent)'});mk('text',{x:xx,y:H-p.b+26,'text-anchor':'middle',fill:'var(--muted)','font-size':10},eventMeta(e.type)[0])});mk('text',{x:8,y:18,fill:'var(--muted)','font-size':11},`${t('duration')} sec`);mk('text',{x:W-8,y:18,'text-anchor':'end',fill:'var(--muted)','font-size':11},`${t('interval')} / ${t('intensity')} 0–10`)}
  function renderReportTable(cs,ev){const host=$('#reportTable'),timeline=[...cs.map(c=>({kind:'contraction',time:c.start,...c})),...ev.map(e=>({kind:'event',...e}))].sort((a,b)=>a.time-b.time);if(!timeline.length){host.innerHTML=`<div class="history-empty">${t('noData')}</div>`;return}let n=0,ds=0,is=0,inN=0;host.innerHTML=timeline.map(it=>{if(it.kind==='event'){const m=eventMeta(it.type);return `<div class="report-row"><b>${fmtClock(it.time)}</b><b>${m[0]} ${escapeHtml(m[1])}</b><span>${escapeHtml(it.note||'—')}</span></div>`}n++;ds+=it.durationSec;if(it.intervalSec!=null){is+=it.intervalSec;inN++}return `<div class="report-row"><b>${fmtClock(it.start)}</b><b>◉ ${fmtDur(it.durationSec)}</b><span>${t('interval')}: ${fmtDur(it.intervalSec)} · ${t('intensity')}: ${it.intensity??'—'}/10<br><small>${t('avgDuration')}: ${fmtDur(ds/n)} · ${t('avgInterval')}: ${fmtDur(inN?is/inN:null)}</small></span></div>`}).join('')}
  async function buildReportHTML(){const {cs,ev}=rangeData(),timeline=[...cs.map(c=>({kind:'contraction',time:c.start,...c})),...ev.map(e=>({kind:'event',...e}))].sort((a,b)=>a.time-b.time),photoMap={};for(const e of ev){if(e.photoId){const b=await getPhoto(e.photoId);if(b)photoMap[e.photoId]=await blobToDataURL(b)}}let n=0,ds=0,is=0,inN=0;const rows=timeline.map(it=>{if(it.kind==='event'){const m=eventMeta(it.type);return `<tr><td>${fmtClock(it.time)}</td><td>${m[0]} ${escapeHtml(m[1])}</td><td>—</td><td>—</td><td>—</td><td>${escapeHtml(it.note||'')}</td><td>${it.photoId&&photoMap[it.photoId]?`<img src="${photoMap[it.photoId]}" class="photo">`:''}</td></tr>`}n++;ds+=it.durationSec;if(it.intervalSec!=null){is+=it.intervalSec;inN++}return `<tr><td>${fmtClock(it.start)}</td><td>Contraction</td><td>${fmtDur(it.durationSec)}</td><td>${fmtDur(it.intervalSec)}</td><td>${it.intensity??'—'}/10</td><td>Avg duration ${fmtDur(ds/n)} · Avg interval ${fmtDur(inN?is/inN:null)} ${escapeHtml(it.notes||'')}</td><td></td></tr>`}).join(''),svg=$('#unifiedChart').outerHTML.replaceAll('var(--primary2)','#b54f17').replaceAll('var(--rose)','#a43a45').replaceAll('var(--surface)','#fffdf8').replaceAll('var(--teal)','#2d6c66').replaceAll('var(--accent)','#f39a32').replaceAll('var(--muted)','#715649').replaceAll('var(--line)','rgba(81,39,15,.16)');return `<!doctype html><meta charset="utf-8"><title>ConTrack report</title><style>body{font:15px -apple-system,system-ui,sans-serif;color:#2c160c;background:#fff6ea;margin:0;padding:24px}.page{max-width:980px;margin:auto;background:#fffdf8;padding:28px;border-radius:24px}h1{margin:0}small{color:#715649}.legend{display:flex;gap:16px;flex-wrap:wrap;margin:12px 0 20px}.chart{overflow:auto;border:1px solid #ead7c7;border-radius:18px;padding:10px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{padding:9px;border-bottom:1px solid #ead7c7;text-align:left;vertical-align:top}.photo{max-width:150px;border-radius:12px}.note{margin-top:16px;color:#715649;font-size:12px}</style><div class="page"><h1>ConTrack by Hanging Sense</h1><small>${new Date().toLocaleString(state.lang)} · ${$('#rangeDescription').textContent}</small><div class="chart">${svg}</div><div class="legend">■ Duration &nbsp; ━● Interval start-to-start &nbsp; ● Pain intensity &nbsp; ◆ Events</div><table><thead><tr><th>Time</th><th>Event</th><th>Duration</th><th>Interval</th><th>Pain</th><th>Trend / Notes</th><th>Photo</th></tr></thead><tbody>${rows}</tbody></table><p class="note">Recorded data only. ConTrack does not diagnose labour or replace professional medical advice.</p></div>`}
  async function reportFile(){return new File([await buildReportHTML()],`ConTrack-report-${new Date().toISOString().slice(0,10)}.html`,{type:'text/html'})}
  async function shareReport(){const file=await reportFile();if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({title:'ConTrack report',files:[file]});return}catch{}}downloadBlob(file.name,file);toast(t('reportReady'))}
  async function exportHtmlReport(){const f=await reportFile();downloadBlob(f.name,f);closeSheets();toast(t('reportReady'))}function downloadReport(){openSheet('#exportSheet')}
  function exportPictureReport(){const {cs,ev}=rangeData(),W=1200,H=Math.max(900,560+(cs.length+ev.length)*34),c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d');x.fillStyle='#fff6ea';x.fillRect(0,0,W,H);x.fillStyle='#2c160c';x.font='800 48px system-ui';x.fillText('ConTrack by Hanging Sense',60,72);x.font='24px system-ui';x.fillStyle='#715649';x.fillText(`${$('#rangeDescription').textContent} · ${new Date().toLocaleString(state.lang)}`,60,110);x.fillStyle='#2c160c';x.font='700 23px system-ui';x.fillText(`${t('contractions')}: ${cs.length}   ${t('avgDuration')}: ${fmtDur(avg(cs.map(v=>v.durationSec)))}   ${t('avgInterval')}: ${fmtDur(avg(cs.map(v=>v.intervalSec)))}   ${t('events')}: ${ev.length}`,60,158);const chartY=200,chartH=300,left=70,right=W-70,base=chartY+chartH;x.strokeStyle='#e1cbb8';for(let i=0;i<=4;i++){const yy=chartY+i*chartH/4;x.beginPath();x.moveTo(left,yy);x.lineTo(right,yy);x.stroke()}const timeline=[...cs.map(v=>v.start),...ev.map(v=>v.time)];if(timeline.length){const min=Math.min(...timeline),max=Math.max(...timeline),span=Math.max(60000,max-min),px=t=>left+(t-min)/span*(right-left),md=Math.max(60,...cs.map(v=>v.durationSec)),mi=Math.max(60,...cs.map(v=>v.intervalSec||0));cs.forEach(v=>{const bh=(v.durationSec/md)*(chartH-25);x.fillStyle='#b54f17';x.fillRect(px(v.start)-8,base-bh,16,bh);if(v.intensity!=null){x.beginPath();x.fillStyle='#a43a45';x.arc(px(v.start),base-(v.intensity/10)*(chartH-25),6,0,Math.PI*2);x.fill()}});const pts=cs.filter(v=>v.intervalSec!=null);if(pts.length){x.strokeStyle='#2d6c66';x.lineWidth=4;x.beginPath();pts.forEach((v,i)=>{const xx=px(v.start),yy=base-(v.intervalSec/mi)*(chartH-25);i?x.lineTo(xx,yy):x.moveTo(xx,yy)});x.stroke()}ev.forEach(v=>{x.fillStyle='#f39a32';x.save();x.translate(px(v.time),base-10);x.rotate(Math.PI/4);x.fillRect(-6,-6,12,12);x.restore()})}x.fillStyle='#2c160c';x.font='700 20px system-ui';x.fillText('■ Duration   ━● Interval start-to-start   ● Pain intensity   ◆ Events',60,535);let y=585,n=0,ds=0,is=0,inN=0;const rows=[...cs.map(v=>({kind:'c',time:v.start,...v})),...ev.map(v=>({kind:'e',...v}))].sort((a,b)=>a.time-b.time);x.font='18px system-ui';for(const it of rows){if(y>H-50)break;if(it.kind==='c'){n++;ds+=it.durationSec;if(it.intervalSec!=null){is+=it.intervalSec;inN++}x.fillStyle='#2c160c';x.fillText(`${fmtClock(it.start)}  Contraction  ${fmtDur(it.durationSec)}  ${fmtDur(it.intervalSec)}  Pain ${it.intensity??'—'}/10`,60,y);x.fillStyle='#715649';x.font='15px system-ui';x.fillText(`Cumulative avg: duration ${fmtDur(ds/n)} · interval ${fmtDur(inN?is/inN:null)}${it.notes?' · '+it.notes:''}`,80,y+22);x.font='18px system-ui';y+=42}else{const m=eventMeta(it.type);x.fillStyle='#2c160c';x.fillText(`${fmtClock(it.time)}  ${m[0]} ${m[1]}${it.note?' · '+it.note:''}`,60,y);y+=32}}c.toBlob(blob=>{if(blob){downloadBlob(`ConTrack-report-${new Date().toISOString().slice(0,10)}.png`,blob);closeSheets();toast(t('reportReady'))}},'image/png',.95)}
  function csv(){const cs=contractions(),rows=[['type','time_iso','duration_sec','interval_start_to_start_sec','pain_intensity','event_type','notes','photo_id']];cs.forEach(c=>rows.push(['contraction',new Date(c.start).toISOString(),c.durationSec,intervalFor(c,cs)??'',c.intensity??'','',c.notes||'','']));events().forEach(e=>rows.push(['event',new Date(e.time).toISOString(),'','','',e.type,e.note||'',e.photoId||'']));rows.sort((a,b)=>a[0]==='type'?-1:new Date(a[1])-new Date(b[1]));return rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n')}
  function downloadBlob(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},800)}
  async function backupObject(session=cur()){const photos={};for(const e of session.events){if(e.photoId){const b=await getPhoto(e.photoId);if(b)photos[e.photoId]=await blobToDataURL(b)}}return {version:'4.4',exportedAt:new Date().toISOString(),session,photos}}
  async function exportBackup(){downloadBlob(`ConTrack-session-backup-${new Date().toISOString().slice(0,10)}.json`,new Blob([JSON.stringify(await backupObject(),null,2)],{type:'application/json'}))}
  async function restoreBackup(file){try{const d=JSON.parse(await file.text()),s=d.session||d.state?.sessions?.[0];if(!s)throw 0;for(const [id,url] of Object.entries(d.photos||{}))await putPhoto(id,await dataURLToBlob(url));state.sessions.push({...s,id:uid('s'),archived:false});state.currentSessionId=state.sessions.at(-1).id;state.activeStart=null;persist();renderAll();toast(t('restored'))}catch{toast('Could not restore backup')}}
  function newSessionFlow(){const s=cur();if(s.contractions.length||s.events.length)openSheet('#sessionSheet');else createNewSession()}function createNewSession(){cur().archived=true;const s={id:uid('s'),createdAt:Date.now(),archived:false,contractions:[],events:[]};state.sessions.push(s);state.currentSessionId=s.id;state.activeStart=null;state.pendingIntensityId=null;persist();closeSheets();renderAll();navTo('track')}async function backupAndNew(){await exportBackup();createNewSession()}function archiveAndNew(){createNewSession()}
  function renderThemes(){const g=$('#themeGrid');g.innerHTML='';THEMES.forEach(th=>{const b=document.createElement('button');b.className=`theme-card${state.theme===th.id?' active':''}`;b.innerHTML=`<div class="theme-preview" style="background:${th.colors[0]};color:${th.colors[1]}"><b>Aa</b><i class="mini-orb" style="background:${th.colors[2]}"></i></div><div class="theme-name">${th.name}<span class="theme-check">${state.theme===th.id?'✓':''}</span></div>`;b.onclick=()=>{state.theme=th.id;persist();applyTheme();renderThemes()};g.appendChild(b)})}
  function navTo(n){$$('.screen').forEach(s=>s.classList.toggle('active',s.dataset.screen===n));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===n));window.scrollTo({top:0,behavior:'smooth'})}function renderAll(){renderTrack();renderHistory();renderSummary();renderThemes()}function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
  $('#timerButton').onclick=toggleTimer;$$('[data-nav]').forEach(b=>b.onclick=()=>navTo(b.dataset.nav));$('#quickSettings').onclick=()=>navTo('more');$('#addEventBtn').onclick=openEvent;$('#sheetBackdrop').onclick=closeSheets;$('#intensitySlider').oninput=syncIntensity;$('#saveIntensity').onclick=saveIntensity;$('#skipIntensity').onclick=skipIntensity;$$('#eventTypes button').forEach(b=>b.onclick=()=>{pendingEventType=b.dataset.eventType;$$('#eventTypes button').forEach(x=>x.classList.toggle('selected',x===b))});$('#eventPhoto').onchange=async e=>{if(e.target.files[0]){pendingPhotoBlob=await compressImage(e.target.files[0]);$('#photoStatus').textContent=t('photoReady')}};$('#saveEvent').onclick=saveEvent;$('#cancelEvent').onclick=closeSheets;$$('[data-range]').forEach(b=>b.onclick=()=>{state.summaryRange=b.dataset.range;persist();renderSummary()});$$('[data-history-filter]').forEach(b=>b.onclick=()=>{state.historyFilter=b.dataset.historyFilter;persist();renderHistory()});$('#shareReport').onclick=shareReport;$('#downloadReport').onclick=downloadReport;$('#exportHtml').onclick=exportHtmlReport;$('#exportPicture').onclick=exportPictureReport;$('#cancelExport').onclick=closeSheets;$('#newSessionBtn').onclick=newSessionFlow;$('#backupAndNew').onclick=backupAndNew;$('#archiveAndNew').onclick=archiveAndNew;$('#cancelNew').onclick=closeSheets;$('#exportBackup').onclick=exportBackup;$('#restoreBackup').onchange=e=>e.target.files[0]&&restoreBackup(e.target.files[0]);$('#exportCsv').onclick=()=>downloadBlob('ConTrack-history.csv',new Blob([csv()],{type:'text/csv;charset=utf-8'}));
  LANGS.forEach(([id,label])=>{const o=document.createElement('option');o.value=id;o.textContent=label;$('#languageSelect').appendChild(o)});$('#languageSelect').value=state.lang;$('#languageSelect').onchange=()=>{state.lang=$('#languageSelect').value;persist();applyI18n()};applyTheme();applyI18n();if(state.activeStart)startTicker();if(state.pendingIntensityId){const c=cur().contractions.find(x=>x.id===state.pendingIntensityId);if(c)openIntensity(c)}if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
})();