(() => {
  const STORE='contrack_hangingsense_v4_5';
  const q=new URLSearchParams(location.search);
  let lang=q.get('lang');
  try{lang=lang||JSON.parse(localStorage.getItem(STORE)||'{}').lang}catch{}
  lang=lang||'en';
  const fallback={en:{wechatId:'WeChat ID',telegramId:'Telegram ID',instagram:'Instagram',email:'Email'},de:{wechatId:'WeChat-ID',telegramId:'Telegram-ID',instagram:'Instagram',email:'E-Mail'},fr:{wechatId:'Identifiant WeChat',telegramId:'Identifiant Telegram',instagram:'Instagram',email:'E-mail'},es:{wechatId:'ID de WeChat',telegramId:'ID de Telegram',instagram:'Instagram',email:'Correo'},zh:{wechatId:'微信 ID',telegramId:'Telegram ID',instagram:'Instagram',email:'电子邮件'},ja:{wechatId:'WeChat ID',telegramId:'Telegram ID',instagram:'Instagram',email:'メール'},ko:{wechatId:'WeChat ID',telegramId:'Telegram ID',instagram:'Instagram',email:'이메일'},ru:{wechatId:'WeChat ID',telegramId:'Telegram ID',instagram:'Instagram',email:'Эл. почта'},ar:{wechatId:'معرّف WeChat',telegramId:'معرّف Telegram',instagram:'Instagram',email:'البريد الإلكتروني'},fa:{wechatId:'شناسه WeChat',telegramId:'شناسه Telegram',instagram:'Instagram',email:'ایمیل'},hi:{wechatId:'WeChat ID',telegramId:'Telegram ID',instagram:'Instagram',email:'ईमेल'}};
  function apply(p){document.documentElement.lang=lang;document.documentElement.dir=['ar','fa'].includes(lang)?'rtl':'ltr';const b=document.getElementById('backBtn');if(b)b.onclick=()=>{location.href='./?screen=more'};const grid=document.getElementById('contactGrid');if(grid){const rows=grid.children;if(rows[0])rows[0].innerHTML=`<span class="emoji">💬</span><span><b>${p.wechatId}</b><br>HangingSense</span>`;if(rows[1])rows[1].innerHTML=`<span class="emoji">✈️</span><span><b>${p.telegramId}</b><br>HangingSense</span>`;if(rows[2])rows[2].innerHTML=`<span class="emoji">📸</span><span><b>${p.instagram}</b><br>@hangingsense</span>`;if(rows[3])rows[3].innerHTML=`<span class="emoji">✉️</span><span><b>${p.email}</b><br>hangingsense@gmail.com</span>`}}
  fetch('i18n-v46.json',{cache:'no-store'}).then(r=>r.json()).then(j=>apply({...fallback.en,...(fallback[lang]||{}),...(j[lang]||{})})).catch(()=>apply({...fallback.en,...(fallback[lang]||{})}));
})();