(() => {
  const STORE='contrack_hangingsense_v4_5'; let packs={};
  const $=s=>document.querySelector(s);
  const EN={reportTitle:'ConTrack report',contractionPattern:'Contraction pattern',rollingTrend:'Rolling 5-value trend',contractions:'Contraction',interval:'Interval',intensity:'Pain intensity',avgDuration5:'Avg duration · last 5',avgInterval5:'Avg interval · last 5',range1h:'Last 1 hour',range3h:'Last 3 hours',rangeDay:'Today',rangeAll:'Entire session',events:'Events',creatorDescription:'Product concept, UX direction and application development.',minutesShort:'min',secondsShort:'s',pee:'Pee',painEvent:'Pain / discomfort',waters:'Waters / fluid',bleeding:'Bleeding',other:'Other'};
  function st(){try{return JSON.parse(localStorage.getItem(STORE)||'{}')}catch{return {}}}
  function t(k){const p=packs[st().lang]||packs.en||{};return p[k]??packs.en?.[k]??EN[k]??k}
  function loc(){return ({de:'de-DE',fr:'fr-FR',es:'es-ES',fa:'fa-IR',zh:'zh-CN',hi:'hi-IN',ar:'ar-SA',ru:'ru-RU',ko:'ko-KR',ja:'ja-JP'})[st().lang]||'en-US'}
  function ses(){const s=st(),a=s.sessions||[];return a.find(x=>x.id===s.currentSessionId)||a.at(-1)||{contractions:[],events:[]}}
  function csAll(){return [...(ses().contractions||[])].sort((a,b)=>a.start-b.start)} function evAll(){return [...(ses().events||[])].sort((a,b)=>a.time-b.time)}
  function fmtClock(ts){return new Date(ts).toLocaleTimeString(loc(),{hour:'2-digit',minute:'2-digit'})} function fmtLong(ts){return new Date(ts).toLocaleDateString(loc(),{day:'numeric',month:'short',year:'numeric'})}
  function fmtDur(sec){if(sec==null||!Number.isFinite(+sec))return '—';sec=Math.round(+sec);const m=Math.floor(sec/60),s=sec%60;return m?`${m} ${t('minutesShort')} ${String(s).padStart(2,'0')} ${t('secondsShort')}`:`${s} ${t('secondsShort')}`}
  function avg(a){const v=a.filter(Number.isFinite);return v.length?v.reduce((x,y)=>x+y,0)/v.length:null} function last5(a){return avg(a.filter(Number.isFinite).slice(-5))}
  function rangeStart(){const r=st().summaryRange||'60';if(r==='all')return -Infinity;if(r==='day'){const d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime()}return Date.now()-Number(r)*60000}
  function rangeData(){const since=rangeStart(),raw=csAll().filter(c=>c.start>=since),ev=evAll().filter(e=>e.time>=since);return {cs:raw.map((c,i)=>({...c,intervalSec:i?Math.max(0,Math.round((c.start-raw[i-1].start)/1000)):null})),ev}}
  function rangeLabel(){const r=st().summaryRange||'60';return r==='60'?t('range1h'):r==='180'?t('range3h'):r==='day'?t('rangeDay'):t('rangeAll')}
  function rangeText(cs,ev){const times=[...cs.map(c=>c.start),...ev.map(e=>e.time)];if(!times.length)return '';const a=Math.min(...times),b=Math.max(...times);return `${fmtLong(a)} · ${fmtClock(a)}–${fmtClock(b)}`}
  function eventMeta(type){return {pee:['🚻',t('pee')],pain:['⚡',t('painEvent')],waters:['💧',t('waters')],bleeding:['●',t('bleeding')],other:['＋',t('other')]}[type]||['＋',t('other')]}
  function css(){const c=getComputedStyle(document.documentElement);return {bg:c.getPropertyValue('--bg').trim()||'#fff6ea',surface:c.getPropertyValue('--surface').trim()||'#fffdf8',text:c.getPropertyValue('--text').trim()||'#2c160c',muted:c.getPropertyValue('--muted').trim()||'#715649'} }
  function loadImg(src){return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}
  function svgImg(svg){return new Promise((res,rej)=>{if(!svg){rej();return}const xml=new XMLSerializer().serializeToString(svg),url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'})),i=new Image();i.onload=()=>{URL.revokeObjectURL(url);res(i)};i.onerror=()=>{URL.revokeObjectURL(url);rej()};i.src=url})}
  function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},800)}
  async function make(){const {cs,ev}=rangeData(),th=css(),W=1400,H=Math.max(1700,1760+(cs.length+ev.length)*34),c=document.createElement('canvas');c.width=W;c.height=H;const x=c.getContext('2d');x.fillStyle=th.bg;x.fillRect(0,0,W,H);x.fillStyle=th.surface;x.fillRect(40,40,W-80,H-80);try{const brand=await loadImg('brand-lockup.png');x.drawImage(brand,80,70,430,130)}catch{}x.fillStyle=th.text;x.font='800 46px system-ui';x.fillText(t('reportTitle'),820,100);x.font='22px system-ui';x.fillStyle=th.muted;x.fillText(rangeLabel(),820,140,500);x.fillText(rangeText(cs,ev),820,174,500);x.fillStyle=th.text;x.font='700 22px system-ui';x.fillText(`${t('avgDuration5')}: ${fmtDur(last5(cs.map(v=>v.durationSec)))}`,80,235);x.fillText(`${t('avgInterval5')}: ${fmtDur(last5(cs.map(v=>v.intervalSec)))}`,520,235);x.fillStyle=th.text;x.font='700 26px system-ui';x.fillText(t('contractionPattern'),80,275);try{const u=await svgImg(window.ConTrackCharts.snapshot('unifiedChart'));x.drawImage(u,80,285,1240,1240*u.height/u.width)}catch{}x.fillStyle=th.text;x.font='700 26px system-ui';x.fillText(t('rollingTrend'),80,1005);try{const tr=await svgImg(window.ConTrackCharts.snapshot('trendChart'));x.drawImage(tr,80,1030,1240,1240*tr.height/tr.width)}catch{}let y=1610;x.font='18px system-ui';const rows=[...cs.map(v=>({kind:'c',time:v.start,...v})),...ev.map(v=>({kind:'e',...v}))].sort((a,b)=>a.time-b.time);for(const it of rows){if(y>H-120)break;x.fillStyle=th.text;if(it.kind==='c')x.fillText(`${fmtClock(it.start)}  ${t('contractions')}  ${fmtDur(it.durationSec)}  ${t('interval')}: ${fmtDur(it.intervalSec)}  ${t('intensity')}: ${it.intensity??'—'}/10`,80,y);else{const m=eventMeta(it.type);x.fillText(`${fmtClock(it.time)}  ${m[0]} ${m[1]}  ${it.note||''}`,80,y)}y+=34}try{const cr=await loadImg('creator-benyima-ai.png');x.drawImage(cr,80,H-100,58,58);x.fillStyle=th.text;x.font='700 18px system-ui';x.fillText('BenYimaAI',150,H-70);x.font='14px system-ui';x.fillStyle=th.muted;x.fillText(t('creatorDescription'),150,H-45)}catch{}c.toBlob(b=>{if(b)download(`ConTrack-report-${new Date().toISOString().slice(0,10)}.png`,b)},'image/png',.95);$('#exportSheet')?.setAttribute('hidden','');$('#sheetBackdrop')?.setAttribute('hidden','')}
  function install(){document.addEventListener('click',e=>{const b=e.target.closest('#exportPicture');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();make()},true)}
  fetch('i18n-v46.json',{cache:'no-store'}).then(r=>r.json()).then(j=>{packs=j;install()}).catch(()=>{packs={en:EN};install()});
})();